---
  - name: Reload ssh
    service:
      # didn't work on Ubuntu systems (only raspbian)
      # name: sshd
      name: ssh
      state: restarted
  - name: restart armbian-ramlog
    systemd:
      name: armbian-ramlog
      state: restarted