---
  - name: deploy apt cacher server
    hosts: dev_server
    gather_facts: yes
    become: yes
    # vars_files:
    #   - vars/dns_load_balancer_provision_vars.yml
    roles:
      - role: deploy_apt-cacher_server