---
# Obsidian Vault Sync (No App Installation)

- name: Clone Obsidian vault from GitHub
  git:
    repo: "{{ obsidian_vault_git_repo }}"
    dest: "{{ obsidian_vault_path }}"
    version: "{{ obsidian_vault_git_branch | default('main') }}"
    force: "{{ obsidian_vault_git_force | default(false) }}"
  become_user: "{{ obsidian_user }}"
  become: yes
  when: obsidian_vault_git_repo is defined
  tags: ['obsidian', 'sync', 'git']

- name: Ensure .gitignore exists for vault
  copy:
    content: |
      # Obsidian workspace files
      .obsidian/workspace.json
      .obsidian/workspace-mobile.json
      .obsidian/cache/
      .trash/
    dest: "{{ obsidian_vault_path }}/.gitignore"
    owner: "{{ obsidian_user }}"
    group: "{{ obsidian_user }}"
    mode: '0644'
    force: no
  become: yes
  when: obsidian_vault_git_repo is defined
  tags: ['obsidian', 'git']

- name: Create cron job to sync vault to Git repository nightly
  cron:
    name: "Obsidian vault Git sync"
    minute: "{{ obsidian_git_sync_minute | default('0') }}"
    hour: "{{ obsidian_git_sync_hour | default('4') }}"
    day: "*"
    month: "*"
    weekday: "*"
    user: "{{ obsidian_user }}"
    job: 'cd {{ obsidian_vault_path }} && git add . && git diff --staged --quiet || (git commit -m "Nightly auto-sync: $(date +\%Y-\%m-\%d)" && git push origin {{ obsidian_vault_git_branch | default("main") }}) 2>/dev/null'
    state: present
  become: yes
  when: 
    - obsidian_vault_git_repo is defined
    - obsidian_auto_git_sync | default(true)
  tags: ['obsidian', 'git', 'cron']

- name: Create default vault directory (for new vaults only)
  file:
    path: "{{ obsidian_vault_path }}"
    state: directory
    mode: '0755'
    owner: "{{ obsidian_user }}"
    group: "{{ obsidian_user }}"
  become: yes
  when: 
    - obsidian_create_vault | default(true)
    - obsidian_vault_git_repo is not defined
  tags: ['obsidian', 'vault']

- name: Display vault sync results
  debug:
    msg:
      - "=== Obsidian Vault Sync Complete ==="
      - "Vault location: {{ obsidian_vault_path }}"
      - "Vault source: {{ 'GitHub: ' + obsidian_vault_git_repo if obsidian_vault_git_repo is defined else 'New vault created' }}"
      - "Git sync: {{ 'Enabled (nightly at ' + obsidian_git_sync_hour | default('4') + ':' + obsidian_git_sync_minute | default('00') + ')' if obsidian_vault_git_repo is defined and obsidian_auto_git_sync | default(true) else 'Disabled' }}"
      - ""
      - "Your vault files are ready!"
      - "Access them at: {{ obsidian_vault_path }}"
  tags: ['obsidian', 'info']