---
  ##Create MySQL server(s)
  - hosts: mysql_servers
    become: yes
    vars_files:
      - vars/mysql_vars.yml
    roles:
      - role: ansible-role-mysql

  ##Create HAProxy Loadbalancer(s)
  - hosts: load_balancers
    become: yes
    vars_files:
      - vars/haproxy_vars.yml
    roles:
      - role: ansible-role-haproxy

  - hosts: k3s_cluster
    gather_facts: yes
    become: yes
    vars_files:
      - inventory/proxmoxCluster/group_vars/all.yml
    roles:
      - role: prereq
      - role: download
      - role: raspberrypi

  - hosts: server_nodes
    become: yes
    vars_files:
      - inventory/proxmoxCluster/group_vars/all.yml
    roles:
      - role: k3s/server_nodes

  - hosts: agent_nodes
    become: yes
    vars_files:
      - inventory/proxmoxCluster/group_vars/all.yml
    roles:
      - role: k3s/agent_nodes
