[unifi_devices]
ubntSW ansible_host=192.168.3.32 ansible_ssh_private_key_file=/home/dax/.ssh/id_rsa
ubntAP ansible_host=192.168.3.10 ansible_ssh_private_key_file=/home/dax/.ssh/id_rsa

[dns_servers]
ds9 ansible_host=192.168.3.4 ansible_ssh_private_key_file=/home/dax/.ssh/id_ecdsa ansible_user=dax
defiant ansible_host=192.168.9.3 ansible_ssh_private_key_file=/home/dax/.ssh/id_ecdsa ansible_user=dax

[load_balancers]
stargazer ansible_host=192.168.9.6
shenzhou ansible_host=192.168.9.5
