[unifi_devices]
ubntSW ansible_host=192.168.3.32 ansible_ssh_private_key_file=/home/dax/.ssh/id_rsa
ubntAP ansible_host=192.168.3.10 ansible_ssh_private_key_file=/home/dax/.ssh/id_rsa

[dns_servers]
ds9 ansible_host=192.168.9.4 ansible_ssh_private_key_file=/home/dax/.ssh/id_ecdsa ansible_user=dax
defiant ansible_host=192.168.9.3 ansible_ssh_private_key_file=/home/dax/.ssh/id_ecdsa ansible_user=dax

[load_balancers]
stargazer ansible_host=192.168.9.6
shenzhou ansible_host=192.168.9.5

[all_raspberry_pis:children]
dns_servers
load_balancers

[ansible_target_servers]
ansible-node-1 ansible_host=192.168.9.116 ansible_python_interpreter=/usr/bin/python2.7
ansible-node-2 ansible_host=192.168.9.114 ansible_python_interpreter=/usr/bin/python2.7

[ansible_target_servers:vars]
ansible_connection=ssh
#ansible_user=serveradmin
#ansible_become_pass=nilok3
