---
collections:
  - name: community.docker
  - name: community.general
  - name: ansible.posix
  - name: artis3n.tailscale

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.docker_arm
  - name: geerlingguy.pip
