---
collections:
  - name: community.docker
  - name: community.general
  - name: ansible.posix

roles:
  - name: artis3n.tailscale
  - name: geerlingguy.docker
  - name: geerlingguy.docker_arm
  - name: geerlingguy.pip
