---
  #sudo ansible-playbook /home/dax/code_base/ansible_projects/playbooks/dns_server_provision/dns_server_provision.yml
  - name: initial setup (defiant & ds9)
    hosts: provision_servers
    gather_facts: true
    become: true
    vars_files:
      - vars/dns_server_provision_vars.yml
    roles: 
      - role: bootstrap_python
      # - role: deploy_apt-cacher_client
      - role: check_if_pi
      - role: provision_server

  - name: pihole and DNS setup (defiant & ds9)
    hosts: post_provision_servers
    gather_facts: true
    become: true
    vars_files:
      - vars/dns_server_provision_vars.yml
    roles:
      - role: check_if_pi
      - role: remove_default_user
      - role: deploy_pihole
      # - role: artis3n.tailscale  #not working currently
      # - role: IronicBadger.figurine
