---
  - name: initial setup (defiant & ds9)
    hosts: provision_servers
    gather_facts: yes
    become: yes
    vars_files:
      - vars/dns_server_provision_vars.yml
    roles: 
      - role: bootstrap_python
      - role: provision_server

  - name: pihole and DNS setup (defiant & ds9)
    hosts: dns_servers
    gather_facts: yes
    become: yes
    roles:
      - role: check_if_raspberry_pi
      - role: deploy_pihole