download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/pfsensible-core-0.6.2.tar.gz
format_version: 1.0.0
name: core
namespace: pfsensible
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.6.2
version_url: /api/v3/plugin/ansible/content/published/collections/index/pfsensible/core/versions/0.6.2/
