# ansible-playbook pfsense_enable_vpn.yml 
---
  - name: pfsense_disable_vpn
    hosts: pfsense_router
    gather_facts: yes
    become: yes
    collections:
      - pfsensible.core.pfsense_alias
    tasks:
      - name: Remove my IP from the pia_redirect_group alias
        pfsense_alias:
          name: pia_redirect_group
          address: 192.168.3.3
          type: host
          state: absent