---
galaxy_info:
  author: your name
  description: Sync Obsidian vault from Git repository
  company: your company (optional)
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
        - "24.04"
  galaxy_tags:
    - obsidian
    - vault
    - sync
    - git
    - notes

dependencies: []
