---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'k3s_frontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 6443
haproxy_frontend_mode: 'http'

# Backend settings.
haproxy_backend_name: 'k3s_backend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

# List of backend servers(server_nodes).
haproxy_backend_servers: 
  - name: k3s-master-1
    address: "{{ hostvars[groups['server_nodes'][0]]['ansible_host'] | default(groups['server_nodes'][0]) }}"
# - name: app2
#   address: 192.168.0.2:80

# Extra global vars (see README for example usage).
haproxy_global_vars: []

# Default haproxy timeouts
haproxy_connect_timeout: 5000
haproxy_client_timeout: 50000
haproxy_server_timeout: 50000
