---
# handlers file for deploy_beszel_agent

  - name: Reload systemd
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Restart beszel-agent
    ansible.builtin.systemd:
      name: beszel-agent
      state: restarted
