---
  # - name: Create proxy configuration file pointing at apt-cacher server
  #   ansible.builtin.copy:
  #     content: 'Acquire::http::Proxy "http://{{ hostvars[groups['dev_server'][0]]['ansible_host'] }}:3142";'
  #     dest: /etc/apt/apt.conf.d/00aptproxy 

  # had to do it this way because of the "" 
  - name: Create proxy configuration file pointing at apt-cacher server
    ansible.builtin.template:
      src: /home/{{ username | lower }}/code_base/ansible_projects/templates/apt-cacher_client_config.j2
      dest: /etc/apt/apt.conf.d/00aptproxy