---
  - name: Create proxy configuration file pointing at apt-cacher server
    ansible.builtin.copy:
      content: "Acquire::http::Proxy "http://{{ hostvars[groups['provision_servers'][0]]['ansible_host'] }}:3142";"
      dest: /etc/apt/apt.conf.d/00aptproxy