---
galaxy_info:
  author: your_name
  description: Disable Armbian ramlog system and configure direct disk logging for Orange Pi devices
  company: your_company
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - orangepi
    - armbian
    - logging
    - ramlog

dependencies: 
  - role: check_if_pi