user: 'dax'
extra_path: '/usr/local/bin'
dotfiles_repo: 'git@github.com:KolinSmith/dotfiles.git'
necessary_packages:
  - wget
  - net-tools
  - zsh
  - powerline
  - fonts-powerline
  - curl
  - git
  - iputils-ping
  - dnsutils
  - acl
  - sudo
  - fzf
  - apt-transport-https
  - unattended-upgrades
  - tmux
  - build-essential
  - unzip
  - cmatrix
  - neofetch
  - pigz
  - locate
  - vim
  - atop
  default_user: ''
