---
  - name: initial setup (stargazer & shenzhou)
    hosts: provision_servers
    gather_facts: yes
    become: yes
    vars_files:
      - vars/dns_load_balancer_provision_vars.yml
    roles:
      - role: bootstrap_python
      - role: deploy_apt-cacher_client
      - role: provision_server

  - name: dnsdist loadbalancer setup (stargazer & shenzhou)
    hosts: load_balancers
    gather_facts: yes
    become: yes
    vars_files:
      - vars/dns_load_balancer_provision_vars.yml
        # necessary_packages:
        # - dnsdist
        # - keepalived
        # tailscale_authkey: '{{ tailscale_auth_key }}'
    roles:
      - role: check_if_raspberry_pi
      - role: artis3n.tailscale 
      - role: deploy_dnsdist
      # - role: IronicBadger.figurine
      - role: remove_default_user