---
- hosts: provision_servers
  roles:
    # - install_exa
  tasks:
      - debug: msg="HERE It is"
        when:  (ansible_machine == "x86_64") or (ansible_machine == "armv7l")

      #when conditional doesn't seem to affect it
      - name: import the install_exa role
        import_role:
          name: install_exa
        when:  (ansible_machine == "x86_64") or (ansible_machine == "armv7l")

      - debug: msg="HERE It is NOW"
        when:  (ansible_machine == "x86_64") or (ansible_machine == "armv7l")
