---

#
#https://www.makeuseof.com/set-up-linux-remote-logging-using-rsyslog/
#

  - name: Install rsyslog
    apt:
      name: rsyslog
      state: present

  - name: Start service rsyslog, if not started
    ansible.builtin.service:
      name: rsyslog
      state: started

  - name: Enable service rsyslog to start on boot
    ansible.builtin.service:
      name: rsyslog
      enabled: yes

  - name: Edit rsyslog.conf to send logs to rsyslog server
    lineinfile:
      path: /etc/rsyslog.conf
      line: "*.* @{{ hostvars[groups['dev_server'][0]].ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:514"

  - name: Restart rsyslog to take new line in conf
    ansible.builtin.service:
      name: rsyslog
      state: restarted