# ansible-playbook pfsense_enable_vpn.yml 
---
  - name: pfsense_enable_vpn
    hosts: pfsense_router
    gather_facts: yes
    become: yes
    collections:
      - pfsensible.core.pfsense_alias
    tasks:
      # - name: Add my IP to pia_redirect_group alias
      #   pfsense_alias:
      #     name: pia_redirect_group
      #     address: 192.168.3.3
      #     type: host
      #     state: present
      #     descr: "List of IPs that will be sent through PIA VPN"

      - name: remove firewall rule for pia
        pfsense_rule:
          name: 'Send PIA alias over VPN'
          action: pass
          interface: lan
          ipprotocol: inet
          protocol: any
          source: pia_redirect_group
          destination: any
          gateway: 'PIA_VPN_VPNV4'
          before: 'Default allow LAN to any rule'
          state: present