---
  - name: server provision
    hosts: post_provision_servers
    gather_facts: yes
    become: yes
    roles:
      - role: check_if_raspberry_pi

  - name: post server provision
    hosts: post_provision_servers
    gather_facts: yes
    become: yes
    roles:
      - role: check_if_raspberry_pi
