---
  - name: server provision
    hosts: provision_servers
    gather_facts: yes
    become: yes
    vars_files:
      - vars/server_provision_script_vars.yml
    roles:
      - role: bootstrap_python
      - role: provision_server

  - name: proxmoxServerProvision
    hosts: provision_servers
    gather_facts: yes
    become: yes
    vars_prompt:
    # - name: hostname
    #   prompt: What do you want to set as the hostname?
    #   private: no
    vars:
