---
- name: piHoleUpdate
  hosts: dns_servers
  gather_facts: yes
  become: yes
  vars_files:
    - ../../group_vars/all/vars.yml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Pull latest Pi-hole image
      command: docker compose pull
      args:
        chdir: "/home/{{ ansible_user }}/docker"

    - name: Restart Pi-hole with new image
      command: docker compose up -d --force-recreate
      args:
        chdir: "/home/{{ ansible_user }}/docker"
