---
  - name: Reload ssh
    service:
      # didn't work on Ubuntu systems (only raspbian)
      # name: sshd
      name: ssh
      state: restarted

  - name: Reload rsyslog
    service:
      name: rsyslog
      state: restarted