---
# handlers file for deploy_print_server

  - name: Restart cups
    ansible.builtin.service:
      name: cups
      state: restarted

  - name: Restart smbd
    ansible.builtin.service:
      name: smbd
      state: restarted

  - name: Restart nmbd
    ansible.builtin.service:
      name: nmbd
      state: restarted
