---
dependencies: []

galaxy_info:
  role_name: figurine
  author: ironicbadger
  description: arsham figurine installation for Linux.
  company: "Midwestern Mac, LLC"
  license: "GPL v3"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
        - bullseye
  galaxy_tags:
    - system
    - login
    - figurine
    - welcome